"""
Tracks which app session (see session_service.py) generated which images,
so "Edit in Canva" can refuse to fetch/upload an image that wasn't
generated by the requesting browser (section 9: "user tries to access
another user's image").

Built on app/services/local_dev_store.py — same DynamoDB swap-in note
applies (see that module's docstring). One record per generation_id
(a whole /generate or /generate/stream call), not one per image, since
every image in a single generation is already scoped to whichever
session made that request.
"""

from typing import Optional

from app.services import local_dev_store

_OWNER_KEY_PREFIX = "image_owner:"
_OWNER_RECORD_TTL_SECONDS = 60 * 60 * 24  # 1 day — matches roughly how long a presigned S3 URL is likely still useful


def record_generation(session_id: str, generation_id: str, image_count: int) -> None:
    """Call once, right after a generation's images are uploaded to S3
    (see app/routes/content.py) — records that `session_id` owns image
    indices 0..image_count-1 under this generation_id."""
    local_dev_store.put_item(
        _OWNER_KEY_PREFIX + generation_id,
        {"session_id": session_id, "image_count": image_count},
        ttl_seconds=_OWNER_RECORD_TTL_SECONDS,
    )


def verify_ownership(session_id: str, generation_id: str, index: int) -> bool:
    """True only if `session_id` is the one that generated
    `generation_id` AND `index` is a real image index within it. Used by
    POST /api/canva/designs/from-images before fetching anything from S3
    or sending anything to Canva — see app/routes/canva.py."""
    record: Optional[dict] = local_dev_store.get_item(_OWNER_KEY_PREFIX + generation_id)
    if record is None:
        return False
    if record.get("session_id") != session_id:
        return False
    if not (0 <= index < record.get("image_count", 0)):
        return False
    return True